codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 60%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

# Define flags for different source directories
flags:
  common:
    paths:
      - COMMON/
    carryforward: true
  neo2par:
    paths:
      - NEO-2-PAR/
    carryforward: true
  neo2ql:
    paths:
      - NEO-2-QL/
    carryforward: true

ignore:
  - "TEST/"
  - "test/"
  - "libneo/"
  - "thirdparty/"
  - "DOC/"
  - "MULTI-SPEC-TOOLS/"
  - "tools/"
  - "build/"
  - "**/*.mod"
  - "**/*.smod"
