codecov:
  require_ci_to_pass: yes
  # Specify directories to search for coverage
  directory: .
  # Specify source directories
  paths:
    - COMMON/
    - NEO-2-PAR/
    - NEO-2-QL/

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 60%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "TEST/"
  - "test/"
  - "libneo/"
  - "thirdparty/"
  - "DOC/"
  - "MULTI-SPEC-TOOLS/"
  - "tools/"
  - "build/"
  - "**/*.mod"
  - "**/*.smod"
