coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 60%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
