name: Run Test on Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  run-golden-record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Make script executable
        run: chmod +x test/golden_record/golden_record.sh

      - name: Run golden record test script
        run: ./test/golden_record/golden_record.sh